#!/bin/sh

# Helper/hack para definir al hint WM_CLASS
# de una aplicacion.

PID=$1
WM_CLASS=$2

WINID=$(wmctrl -lpx | grep $PID | cut -d' ' -f 1)
xprop -id ${WINID} -f WM_CLASS 8s -set WM_CLASS $WM_CLASS
